apiVersion: apps/v1
kind: Deployment
metadata:
  name: webfilm-deployment
  labels:
    app: webfilm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webfilm
  template:
    metadata:
      labels:
        app: webfilm
    spec:
      containers:
      - name: webfilm
        image: 4miby/webfilm:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: webfilm-service
  labels:
    app: webfilm
spec:
  selector:
    app: webfilm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

